### PR TITLE
Added new parts to virtual machine definition model

### PR DESCRIPTION
**Pull request by ruthger**
- Added in the Virtual Machine Definition Model:
- Node CPU
- Node CPU > Model
- Node CPU > Features
- Node CPU > Vendor
- Node CPU > Topology
- Node Controller > Driver
- Node Feature > HyperV
- Node Feature > HyperV > Relaxed
- Node Feature > HyperV > Spinlock
- Node Feature > HyperV > Vapic
- Attribute Feature > Apic @ eoi
- Attribute Device > DiskDriver > discard 
- Attribute Device > DiskDriver > io
- List value Clock > Timer > HyperV

This should add most of the missing xml nodes in the definition. 
The only one missing that I can think of the the smbios part, but I'm working on that.

### CODE REVIEW

**Comment by CyrilPeponnet** [comment]
Feel free to dump the entire model if you are motivated :) Thanks!

**Comment by ruthger** [comment]
I will try to add some more nodes to the model (Numa, SMBios), if you try to add them to the GUI.. At least some of the importent ones (HyperV, io, discard, cpu topology, USB model) 
I really like this Archipel Project and I think it is the best web interface for libvirt. Lean and Mean. Just a bit sad that the development is stalling.

**Comment by CyrilPeponnet** [comment]
Sounds like a good deal. And yes this is the best :p Development take time and human resources... we lake both of them. This may change in the future without any promise but we have plan. And an updated libvirt model is part of the plan as well. Thanks for contributing :)

**Comment by primalmotion** [comment]
> but we have plan.

And what a plan ;)

**Comment by CyrilPeponnet** [comment]
I'm reviewing it. There some few changes to make. I will push you the details when I'll be done. Are you able to test your changes?

**Comment by ruthger** [comment]
I'm still having trouble to get Archipel Client build. I'm using ArchLinux and it's not playing nice for the build script.

**Comment by ruthger** [comment]
If you can provide me a build version I have the time to test it.

**Comment by CyrilPeponnet** [comment]
I will but for now it doesn't build. (Errors and typo).

**Comment by ruthger** [comment]
Please send me the list of errors and I will try to fix them.. Or if you can provide a pre configured vm machine (qemu/qcow2) so I can build and correct it myself.

**Comment by CyrilPeponnet** [comment]
I’m building on OSX. Still working on it but hard to find the time this week..

**Comment by ruthger** [comment]
Any news?? Please just send me the list error so I can try fix and we can continue..

**Comment by CyrilPeponnet** [comment]
Sorry for the late reply, I started to take a look on your PR but then I had to deal with hotter topics. The best is to manage to have a proper build environment. This should work fine on ubuntu or centos (and should also work on archlinux I guess).

**Comment by HTPC-Schrauber** [comment]
Any progress on this?
I would love to see the options for CPU selection in the UI.

**Comment by CyrilPeponnet** [comment]
I'd love to spend some time on this part but unfortunately hard to find some free time. :/

This is not too complex but extremely boring.

But fell free to give a try :) We are laking contributors in here.

**Comment by HTPC-Schrauber** [comment]
OK, I tried to look into this.
I tried to build on an ubuntu machine. But I get one error after another.
I must say, I have no skills in node.js. So there is not much I can do in coding.

The frist errors I was able to fix. There where some semicolon in wrong position or open brackets.
But now I am on the VirtualMachineDefinition and  there are missing files. There are files imported like TNLibvirtDomainCpuType.j, TNLibvirtDomainCpuLoader.j or TNLibvirtDomainCpuNvram.j but they are missing.

So I this now gets more complex than some brackets or semicolon.

@ruthger: You can build this youself on a linux machine.
- Run 'sudo bootstrap' in the ArchipelClient directory. 
- answer the question to build cappuccino with y, the others with n
- answer the questions to put cappucino into you path with yes
- installation failes, but this is no problem
- logout and in again the get the updated path
- Run bootstrap again (without root is OK)
- Answer the all the questions with y, except the one to build cappuccino

Thats it.
Afterwrds you can run 'buildArchipel -bag' to build ArchipelClient.

**Comment by CyrilPeponnet** [comment]
@ruthger I will close this one as it's not building and conflict with @HTPC-Schrauber changes. If you still want to add those features, you are welcome to work on top of the master branch :)

**Comment by YATV** [comment]
How to use this is configurations?

**Comment by HTPC-Schrauber** [comment]
I added CPU and soundcard definition to the virtual machine definition model.
This means, that this defintions are known to Archipel, but for now they are not configurable through the ArchipelClient.
You can make use of this defintions directly in the VM XML defintion (through virsh edit from the commandline) and Archipel will not remove them when making changes via ArchipelClient.

Without the changes to the virtual machine definition model, those changes where removed when making changes via ArchipelClient.

**Pull request closed without merging**
